name: CI
on:
  schedule:
    - cron: "* 12-23 * * *"
  workflow_dispatch:
jobs:
  calculteUserStreak:
    #uses: colchetedao/streakCounter/.github/workflows/saveContributionCountPerDay.yml@main
    uses: colchetedao/actionPlayground/.github/workflows/workflow-called.yml@main
    secrets: inherit
  build:
    environment:
      name: ${{ github.ref_name }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run a multi-line script
        run: |
          bash checkCommit.sh ${{  vars.GIT_USER }} ${{ secrets.WEBHOOK_URL }} ${{ vars.MIN_DAILY_COMMIT_COUNT }}
      - name: Upload to git
        id: uploadGit
        run: |
          if [[ `git status --porcelain` ]]; then
            git config --global user.name "juancolchete"
            git config --global user.email "juancolchete@gmail.com"
            git add . 
            git commit -m "file: ${{github.event.head_commit.message}}"
            git push
          else
            echo "no changes to push"
          fi
